### ISSUE TITLE
JECC - nach dem Verschieben eines Datenobjekts in ein Datenverzeichnis wird das darunter liegende Clean Object im Baum nicht mehr angezeigt

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1016]
nach dem Verschieben eines Datenobjekts in ein Datenverzeichnis wird das darunter liegende Clean Object im Baum nicht mehr angezeigt

**Comment by gschutz84** [comment]
programm neustarten als workaround, richtig böse wird es wenn das mehr tiefe hat

**Comment by EnvidatecFS** [comment]
Besseres workaround ist glaube ich einen Filter auszuwählen und dann wieder zurückzusetzen.

**Comment by EnvidatecNH** [comment]
Die Workarounds sind bekannt, ist aber einfach lästig und schon lange so

**Comment by EnvidatecNH** [comment]
Es ist wieder da
