### ISSUE TITLE
JECC - Diagramme - Bubble-Diagramme könnten wie Chart-Diagramme auch eine Toplegende haben

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1043]
Bubble-Diagramme könnten wie Chart-Diagramme auch eine Toplegende haben -> zeigt den Zahlenwert an, ...

**Comment by gschutz84** [comment]
der zahlenwert wird bei mouse hover auf einer blase angezeigt. tabelle scheint nicht wirklich sinn zu machen, was soll man da sehen?

**Comment by EnvidatecNH** [comment]
z.B. den x-Wert, y-Wert und die Häufigkeit, ggf. noch die Standardabweichung wenn man noch ein Feature wie "Clustern bei sehr ähnlichen, wenn auch nicht gleichen Werten"
