### ISSUE TITLE
JECC - Diagramme - Analyse laden Dialog -> die Uhrzeiten bei der freien Zeitwahl können nicht über Tastatur, sondern nur über die Klick-GUI geändert werden

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1061]
Analyse laden Dialog -> die Uhrzeiten bei der freien Zeitwahl können nicht über Tastatur, sondern nur über die Klick-GUI geändert werden

**Comment by gschutz84** [comment]
lässt sich nicht reproduzieren
