### ISSUE TITLE
JECC - Diagramme - es scheint als kann man Datenreihen, die nur Rohdaten haben nicht in Analysen auswählen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1079]
es scheint als kann man Datenreihen, die nur Rohdaten haben nicht in Analysen auswählen -> soll das so sein?

**Comment by gschutz84** [comment]
wenn ein clean data object existiert und das leer ist, kann man die datenreihe nicht auswählen.
