### ISSUE TITLE
JECC - Diagramme - Blasendiagramm nutzt nicht den y-Achsen-Bereich nicht  optimal

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1099]
Blasendiagramm nutzt nicht den y-Achsen-Bereich nicht  optimal -> die y-Achse geht weitaus höher als nötig und zeigt auch einen negativen Bereich an, obwohl es keine negativen Werte gibt

**Comment by gschutz84** [comment]
nicht reproduzierbar
