### ISSUE TITLE
JECC - Dashboard - Abhängig vom Zeitfilter werden wenige oder viele Felder als n.a. angezeigt

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1139]
Abhängig vom Zeitfilter werden wenige oder viele Felder als n.a. angezeigt -> TBD

**Comment by EnvidatecFS** [comment]
Mit der version 3.8.24+ ? Kann ich nicht nachvollziehen. Am besten du zeigst mir das morgen am usecase.

**Comment by EnvidatecNH** [comment]
Nein, der Fehler wurde vor 2 Wochen mit einer Version <3.8.24 gemeldet, mit der 3.8.24 scheint das Problem behoben zu sein
