### ISSUE TITLE
JECC - Calc-Editor - wenn man eine Datenreihe als Eingang auswählt, wird in der Standardansicht die Rohdatenreihe und nicht die Cleandatenreihe ausgewählt

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1157]
wenn man eine Datenreihe als Eingang auswählt, wird in der Standardansicht die Rohdatenreihe und nicht die Cleandatenreihe ausgewählt -> es sollte sorum sein, dass Clean das normale ist, sollte man roh haben wollen, muss man über "alle Attribute" gehen

**Comment by EnvidatecNH** [comment]
Bei der Auswahl der Ausgangsvariable wird die Cleandatenreihe auch angezeigt (macht hier aber keinen Sinn), bei der Auswahl der Eingangsvariable wird sie nicht angezeigt -> wenn es genau andersrum wäre, wäre es auch OK

**Comment by gschutz84** [comment]
du wolltest, dass man möglichst einfach klickt für daus, also wählt man die rohdaten aus, bei denen der name aussagekräftig ist, und bekommt die clean daten autom. außer man stellt den filter um und wählt die rohdaten manuell
