### ISSUE TITLE
JECC - Diagramme - es muss eine Rückmeldung kommen, wenn eine Notiz auf Grund mangelnder Rechte nicht übernommen wird

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1178]
es muss eine Rückmeldung kommen, wenn eine Notiz auf Grund mangelnder Rechte nicht übernommen wird -> aktuell gibt es kein Feedback, aber es erscheint keine Notiz

**Comment by EnvidatecFS** [comment]
Für eine ordentliche Lösung müssten wir die JEAPi-WS auf bohren was ich eh gerne mal machen würde.

**Comment by EnvidatecNH** [comment]
Wurde geschlossen, aber der Fix gehört nicht zu dem Problem

**Comment by gschutz84** [comment]
die anzeige stimmt nicht wenn du mit der maus drüber gehst, siehst du dass da eine ganze reihe commits drin sind. einer davon war das
