### ISSUE TITLE
Es muss eine Möglichkeit geben als Benutzer Notizen anzulegen ohne dafür Schreibzugriff auf Raw oder Clean Data zu haben

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1179]
Es muss eine Möglichkeit geben als Benutzer Notizen anzulegen ohne dafür Schreibzugriff auf Raw oder Clean Data zu haben -> TBD

**Comment by EnvidatecFS** [comment]
Recht komplex Problem. 
Aus Sicherheitsgründen kann der Webservice da keine Ausnahme machen, es muss also bei anlegen der der Objekte durche den Admin nur die damit verbunden Rechte verteilen. Da die UI nicht weiß für welche Unser müsste ein Wizzard beim anlegen durch einen Admin den Admin User fragen ob und wenn welche User/Gruppe.

**Comment by EnvidatecNH** [comment]
Könnte es evtl. eine Lösung sein, dass die Notiz nicht unterhalb des Data Objects gespeichert wird, sondern an einem ganz anderen Ort wie Z.B. "Note Directory" auf dem ganz andere Rechte gelten können und dann hat ein Data Object einen Verweis auf seine Notiz wenn eine existiert?

**Comment by EnvidatecFS** [comment]
Ja, technisch möglich macht Allerdings das System komplexer.
