### ISSUE TITLE
JECC - Dashboard - Seit die Ladeanzeigen in den Torten sind, klappt sie nicht mehr fancy auf, kann man beides haben?

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1182]
Seit die Ladeanzeigen in den Torten sind, klappt sie nicht mehr fancy auf, kann man beides haben?

**Comment by EnvidatecFS** [comment]
was meist du damit genau?
Die Animation kommt nur das allererste mal und das geht immer noch. Ich vermute der deine GUI ist nur zu lahm.

Ich kann mal schauen ob man das optimieren kann.
