### ISSUE TITLE
Multilaguage - wenn ein einzelnes i18n fehlerhaft ist, fällt die gesamte Übersetzung aus -> das sollte abgefangen werden

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1192]
wenn ein einzelnes i18n fehlerhaft ist, fällt die gesamte Übersetzung aus -> das sollte abgefangen werden

**Comment by gschutz84** [comment]
das sollte sich auf das i18nWS für die klassen beziehen, die normale i18n sollte das schon machen
