### ISSUE TITLE
JECC - Dasboards - das Bild wird extrem unscharf, wenn man nach der Änderung den Konfigurationsdialog schließt

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1199]
das Bild wird extrem unscharf, wenn man nach der Änderung den Konfigurationsdialog schließt

**Comment by EnvidatecNH** [comment]
Dashboard laden, Schlossbutton klicken, Konfigdialog öffnen, eine Sache ändern, Konfigdialog schließen -> alles verschwommen

**Comment by EnvidatecFS** [comment]
Kann ich nicht reproduzieren.

**Comment by EnvidatecFS** [comment]
Kann es sein das du den Highlight Button gedrückt hattest?  Wenn ja kann ich einbauen das wenn der Settings Dialog geschlossen wird Highlight deaktiviert wird.

**Comment by EnvidatecNH** [comment]
ja genau sowas wird das sein, sollte die Lösung sein
