### ISSUE TITLE
Ist es aktuell protokollierbar wer was wann erstellt / geändert / manipuliert hat?

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1210]
Ist es aktuell protokollierbar wer was wann erstellt / geändert / manipuliert hat?

**Comment by EnvidatecFS** [comment]
Nein. Hierfür wäre ein weiterer Layer in der API/WebService/DB nötigt welcher einiges an Performance fressen würde.

Wir könnten mit bestehenden Mitteln höchstens ausgewählte Aktionen beim User mitloggen, diese wären aber nicht vollständig und auch nicht manipulationssicher.
