### ISSUE TITLE
JECC - Reporting - viele Objekte zeigen kein Report obwohl welche da sind

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1230]
viele Objekte zeigen kein Report obwohl welche da sind

**Comment by gschutz84** [comment]
das habe ich gestern gesagt, die liste für die berichte enthält alle für den benutzer verfügbaren berichte, die box mit den erstelldaten enthält nur dann etwas, wenn das neue pdf attribut mindestens eine pdf enthält

**Comment by EnvidatecNH** [comment]
Duplicate of #1231
