### ISSUE TITLE
JECC - Diagramme - Balkendiagramm lässt sich nicht einstellen / scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1262]
Balkendiagramm lässt sich nicht einstellen / scheint nicht zu funktionieren

**Comment by gschutz84** [comment]
da gibt es nichts einzustellen, das balkendiagramm zeigt den letzten wert der datenreihe an und aktualisiert sich automatisch

**Comment by EnvidatecNH** [comment]
dann geht es nicht in der aktuellen Produktivversion. Habe verschiedene Datenreihen in verschiedenen Zeitbereichen geladen, kriege aber nur ein leeres Diagramm
