### ISSUE TITLE
JECC - Manuelle Dateneingabe -> Plausibilitätsprüfungen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1332]
Die manuelle Dateneingabe könnte die Eingabe auf Plausibilität prüfen und ggf. einen Hinweis an den Benutzer ausgeben, ob der Wert so wirklich importiert werden soll, z.B. in den Fällen

- Zieldatenreihe ist ein Zählerstand, der neue Zählerstand ist aber kleiner dem letzten
- Eingabewert (bzw. die Differenz zwischen Eingabe und letzten Wert wenn es ein Zählerstand ist) überschreitet L1/L2

**Comment by gschutz84** [comment]
Erste Bedingung ist kein Problem, weil alle Clean Data Kinder den Schalter haben, zweite Bedingung ist schlecht, da wenn es mehrere Clean Data Objekte mit unterschiedlicher Aggregation gibt, die Grenzen unterschiedlich sein können

**Comment by EnvidatecNH** [comment]
Die Prüfung kann je Clean Data Objekt erfüllen, wenn mehr als 1 existiert kann es auch mehr als 1 Warnung geben
