### ISSUE TITLE
JECC - Diagramme - Heatmap hat Probleme mit allen Zeitfilter, die sich nicht auf einen ganzen Monat beziehen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1340]
Heatmap hat Probleme mit allen Zeitfilter, die sich nicht auf einen ganzen Monat beziehen -> z.B. letzt 30/7 Tage

**Comment by gschutz84** [comment]
duplicate JECC - Charts - Heatmap - Timeframes greater then months are not working right #1327
