### ISSUE TITLE
JECC - Diagramme/Dashboard rufen unterschiedliche "Wollen Sie speichern"-Dialoge auf

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1344]
Diagramme/Dashboard rufen unterschiedliche "Wollen Sie speichern"-Dialoge auf -> kann man das vereinheitlichen?

**Comment by EnvidatecFS** [comment]
Ist der mehr oder weniger der selbe Dialog da es ein Code-Clone ist. Der einzige unterschied ist das der eine die Komponente horizontal maxed, scheint später dazu gekommen zu sein.

Man kann natürlich einen Dialog daraus machen muss man aber größer umbauen damit er generisch ist.
