### ISSUE TITLE
JEVis Login - es wäre schön wenn man ein alternatives Bild für den Login Dialog im JEVis konfigurieren könnte [niedrige Prio]

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1351]
es wäre schön wenn man ein alternatives Bild für den Login Dialog im JEVis konfigurieren könnte

**Comment by EnvidatecFS** [comment]
Können wir bereits seit Anbeginn der Zeit.
Mit den Startoptionen "fxlogin.css" und "fxlogin.logo"

**Comment by EnvidatecNH** [comment]
Ich weiß und seit Anbeginn der Zeit nutzt das niemand, weil man das css anfassen muss. Daher war meine Frage / Feature Request ob man in Zukunft das Bild einfach in JEVis hochlädt (Systemebene) and that's it. Prio wie geschrieben aber niedrig
