### ISSUE TITLE
JECC - Copy&Paste geht innerhalb von Analyse-Ordnern nicht

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1357]
Copy&Paste geht innerhalb von Analyse-Ordnern nicht -> weder mit Strg+c/v noch mit Kontextmenü

**Comment by EnvidatecFS** [comment]
Konnte Fehler auf Zwei Server nicht nachvollziehen. Bitte Möglichkeit zum reproduzieren finden.

**Comment by gschutz84** [comment]
duplicate of JECC - Kopieren & Einfügen klappt nicht in einem Analyse Ordner #1172
