### ISSUE TITLE
[JECC - wenn man Einheiten einstellt bleibt das Präfix (Kilo, ...) unbeachtet [Hohe Prio]

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1364]
wenn man Einheiten einstellt bleibt das Präfix (Kilo, ...) unbeachtet - Blocker, da sich so keine Daten einrichten lassen

**Comment by gschutz84** [comment]
erst die einheit einstellen, dann das prefix. funktioniert hier, irgendwas sonst gemacht?

**Comment by EnvidatecNH** [comment]
Hab ich in der selben Reihenfolge gemacht und dann "von links nach rechts übertragen" gedrückt. In der drop-down Box links steht dann KILO, aber nicht im Einheitenfeld unten (nur Wh). Auf der übertragenen rechten Seite steht weder in der Box noch im Einheitenfeld KILO bzw 'k'

**Comment by gschutz84** [comment]
das es im einheitenfeld nicht steht ist richtig, im symbol oder label feld steht das was angezeigt wird, da müsste dann das k drin stehen. warum es nicht übertragen wird ist allerdings merkwürdig. ich teste morgen mal, vielleicht passiert es nur bei vorher nicht eingestellten einheiten (null) allerdings hatte ich eine neue angelegt und da ging es. mal sehen
