### ISSUE TITLE
JECC - Diagramme - Ein "zeitliche Verlinkung auflösen"-Knopf könnte praktisch sein

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1383]
Ein "zeitliche Verlinkung auflösen"-Knopf könnte praktisch sein -> TBD (steht im Zusammenhang mit verschiedenen Zeiträumen)

**Comment by gschutz84** [comment]
duplicate of JECC - Charts - Button to disable/enable linked zoom #745
