### ISSUE TITLE
JECC - JENotifier Service zeigt an, dass er deaktiviert ist obwohl er an ist

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1384]
JENotifier Service zeigt an, dass er deaktiviert ist obwohl er an ist

**Comment by EnvidatecFS** [comment]
Wie genau meist du das, wo zeigt er das an?
Vermute ich richtig wenn du im JEVisCC unter Services das "enabled" meinst ?
