### ISSUE TITLE
JECC - Windows start error

### ISSUE THREAD

**Issue by gschutz84** [OpenJEVis/JEVis#140]
Aug 06, 2018 1:30:09 PM java.util.prefs.WindowsPreferences <init> WARNUNG: Could not open/create prefs root node Software/JavaSoft/Prefs at root 0x800000002. Windows RegCreateKeyEx(...) returned error code 5.

**Comment by EnvidatecFS** [comment]
When does this happen? Does the program crash?
I guess its related to https://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node and happen wile reading and writing the configuration for user&last file.

**Comment by EnvidatecFS** [comment]
When does this happen? Does the program crash?
I guess its related to https://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node and happen wile reading and writing the configuration for user&last file.
