### ISSUE TITLE
JECC - Diagramme + Dashboard - Tickerbeschriftung nur am Anfang und Ende

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1470]
Im Dashboard (Ansicht Woche) ist die x-Achse nur ganz am Anfang und Ende mit einem Datum beschriftet. Bei Analysen ist die Beschriftung nur im 1 Chart richtig, bei den Charts > 1tritt das selbe Problem wie beim Dashboard auf.

**Comment by EnvidatecNH** [comment]
Sieht besser aus, aber nicht in allen Varianten. (Dashboard)

Beobachtung: 
1. Start mit Woche (klappt)
2. Umschalten auf Jahr 2020 (klappt)
3. Umschalten auf Jahr 2019 -> wieder nur am Anfang und Ende ein Datum

Außerdem (gibt es evtl ein separates Ticket) kann man nicht erkennen auf welchen Strich sich die Datumsangabe bezieht (in Analyse ist der jeweilige fett)

**Comment by EnvidatecFS** [comment]
Gerfixed durch neue graph lib
