### ISSUE TITLE
JECC - Manuelledateneingabe-Dialog sollte die Einheit anzeigen in der man den Wert eingibt

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1490]
Manuelledateneingabe-Dialog sollte die Einheit anzeigen in der man den Wert eingibt

**Comment by gschutz84** [comment]
im normalfall sind es zählerstände also einheitenlos? soll die clean daten einheit dann angezeigt werden?

**Comment by EnvidatecNH** [comment]
Ein Zählerstand ist eigentlich nie einheitenlos. Bei Impulszählerständen lassen wir die Einheit weg, wobei man da eigentlich auch Impuls o.ä. hinschreiben könnte
