### ISSUE TITLE
JECC - Alarme - geprüfte Alarme anzeigen geht nicht

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1512]
geprüfte Alarme anzeigen geht nicht -> es wird eine neue Tabelle erstellt, aber es sind trotzdem nur ungeprüfte Alarme enthalten

**Comment by gschutz84** [comment]
richtiger zeitbereich ausgewählt? ansonsten nicht reproduzierbar

**Comment by EnvidatecNH** [comment]
1. Alarme Laden von Gestern (08.1.2020)
2. ein Teil der Alarme bestätigen
3. auf "geprüfte ... anzeigen" klicken -> werden nicht angezeigt

**Comment by gschutz84** [comment]
also erstmal bleiben die geprüften drin bis das erste mal neu geladen wird. dann werden sie nicht mehr angezeigt, klickt man dann auf geprüfte anzeigen werden sie angezeigt. natürlich wenn gerade wieder ein alarm bei der gruppe aufgetreten ist werden sie wieder ungeprüft gesetzt

**Comment by EnvidatecNH** [comment]
Das kann es nicht sein, die Liste der ungeprüften war deutlich kürzer, d.h. die können nicht da wieder drin sein. Bitte notieren und dann versuchen wir das mal gemeinsam zu reproduzieren
