### ISSUE TITLE
JECC - "Berechnung zurücksetzen" hat kein Effekt

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1519]
"Berechnung zurücksetzen" hat kein Effekt -> musste die Zieldatenreihe und Clean manuell löschen

**Comment by gschutz84** [comment]
unter Daten irgendwas auswählen, strg+shift+j drücken, Zeitbereich auswählen und OK -> alle Daten/Clean Daten unter dem ausgewählten Objekt die Berechnungen sind werden im Zeitbereich gelöscht.
