### ISSUE TITLE
JECC - Analysen - Speichern von Analysen geht nicht

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1604]
Speichern von Analysen geht nicht -> es wird ein Objekt angelegt, aber die Attribute sind leer

**Comment by EnvidatecFS** [comment]
Nullpointer im SaveAnalysisDialog.java:257 mit auskommentieren der Zeile geht das speichern wieder aber da ich keine Ahnung der Nebenwirkungen änder ich das ermal nichts.
