### ISSUE TITLE
JECC - Analysen - Rechte Maus - Wert hinzufügen

### ISSUE THREAD

**Issue by EnvidatecFS** [OpenJEVis/JEVis#1608]
Wenn wir schon den Notizen Dialog auf der rechten Maus haben sollten wird in dem Dialog auch den angezeigten Mess-Wert hinzufügen.

**Comment by gschutz84** [comment]
wozu, der steht in der tabelle? bzw. hat man sich gerade den wert angesehen und innerhalb von einer sekunde sollte man den nicht vergessen? überfrachtet nur weiter den dialog
