### ISSUE TITLE
JEDataProcessor - acceleration check

### ISSUE THREAD

**Issue by EnvidatecFS** [OpenJEVis/JEVis#1647]
Support an acceleration check. This functions checks if an value changed to fast against an fixed limit.

For example:
- Datapoint is an outside temperature.
- The acceleration limit is 10°C
- Normaly the outside  temeratur can not change more the 2°C per 15 minutes

So if the temerature now changed nore the 10°C in one metering interval we know that something went wrong. The same logic can help preventing some metering errors where we have an big spike.

**Comment by gschutz84** [comment]
duplicate #184
