### ISSUE TITLE
Diagramme - wenn man async-Daten und zeitliche Daten in einem Diagramm hat, funktioniert der Cursor-Wert für die zeitlichen Daten nicht richtig

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1710]
wenn man async-Daten und zeitliche Daten in einem Diagramm hat, funktioniert der Cursor-Wert für die zeitlichen Daten nicht richtig

**Comment by gschutz84** [comment]
duplicate of #1712
