### ISSUE TITLE
JECC - Login - Link auf "neue Version" funktioniert scheinbar nicht

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1737]
Link auf "neue Version" funktioniert scheinbar nicht -> startet dann wieder die alte version

**Comment by EnvidatecFS** [comment]
Der link ruft nur die startseite des jeweiligen JEVis server auf. Updaten kann er nicht.

**Comment by EnvidatecNH** [comment]
Ich hab grad keine Idee wie ich das reproduzieren kann, aber ich glaube das ging bei einem der Inhouse Systeme auch nicht.

 

--

Nils Heinrich

Envidatec GmbH

JEVis Solutions Dept.

Veritaskai 2

D-21079 Hamburg

 

phone: +49 (0)40 / 300 857 - 42

fax: +49 (0)40 / 300 857 - 70

email:  <mailto:nils.heinrich@envidatec.com> nils.heinrich@envidatec.com

skype: nils.heinrich@envidatec.onmicrosoft.com

 

 <http://www.envidatec.com/> http://www.Envidatec.com

 <http://www.iso50001.de/> http://www.ISO50001.de

 <http://www.jevis.de/> http://www.JEVis.de

 

managing directors:

Dipl.-Ing. Thomas Frank, Dipl.-Ing. Peer Schuback commercial register: Hamburg HRB 80977

VAT-id-No.: DE 216 522 473

tax-No.: 47/718/00195

 

--------------------------------------------------------------------------------

We're using GnuPG cryptography:  <http://www.gnupg.org/> http://www.gnupg.org Find our public keys at pool.sks-keyservers.net (Search for Keys via 'envidatec.com’)

--------------------------------------------------------------------------------

 

 

Von: Florian Simon <notifications@github.com> 
Gesendet: Montag, 4. Mai 2020 13:54
An: OpenJEVis/JEVis <JEVis@noreply.github.com>
Cc: Nils Heinrich <nils.heinrich@envidatec.com>; Author <author@noreply.github.com>
Betreff: Re: [OpenJEVis/JEVis] JECC - Login - Link auf "neue Version" funktioniert scheinbar nicht (#1737)

 

Der link ruft nur die startseite des jeweiligen JEVis server auf. Updaten kann er nicht.
