### ISSUE TITLE
Messstellen - Eingabe von Zählereständen bei Zählerwechsel - ist es möglich die Auswahl "Datum, Tag, Monat, Jahr" von der Periode der Zieldatenreihe abhängig zu machen?

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1823]
Eingabe von Zählereständen bei Zählerwechsel - ist es möglich die Auswahl "Datum, Tag, Monat, Jahr" von der Periode der Zieldatenreihe abhängig zu machen?

niedrige Prio -> TBD

**Comment by gschutz84** [comment]
ja
