### ISSUE TITLE
JEDataProcessor - detect and dismiss values if the increasing from the previous value to the next value is unrealistic

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#184]
Detect and dismiss values if the increasing from the previous value to the next value is unrealistic -> can be defined in a factor or percentage -> a outdoor temperature will not be the double as the sample before

**Comment by gschutz84** [comment]
This should be done with the limits configuration?

**Comment by EnvidatecNH** [comment]
In the configuration, but will be an extra option, thus not part of the "level 1" or "level 2" logic

**Comment by gschutz84** [comment]
Low prio
