### ISSUE TITLE
JECC - Analysen laden im falschen Zeitbereich beim erstellen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1845]
Wenn man eine neue Analyse erstellt oder auch eine temporäre Analyse mittels Button startet wird oben der Zeitbereich "heute" angezeigt, aber von heute bis 01.01.2001 geladen

![grafik](https://user-images.githubusercontent.com/6728123/90624850-eb1f2200-e218-11ea-866c-8feba16d82ad.png)

**Comment by gschutz84** [comment]
Das passiert, wenn in dem eingestellten Zeitbereich keine Daten vorhanden sind
