### ISSUE TITLE
JECC - Analysen - "Reset Zoom"-Button im Top-Menü hat keinen Effekt

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1882]
"Reset Zoom"-Button im Top-Menü hat keinen Effekt

**Comment by gschutz84** [comment]
es gibt keinen reset zoom button

**Comment by EnvidatecNH** [comment]
![grafik](https://user-images.githubusercontent.com/6728123/93942810-74060d80-fd31-11ea-8b40-6e574dd13db9.png)
