### ISSUE TITLE
JECC - Mouse-Tooltip vom "Online"-Status sieht zu kryptisch aus [Prio Niedrig]

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1890]
![grafik](https://user-images.githubusercontent.com/6728123/94286816-ce7fb380-ff55-11ea-9189-5fdc803e43fe.png)

**Comment by EnvidatecFS** [comment]
Was stellst du dir den als weniger kryptisch vor?
