### ISSUE TITLE
JEDataCollector - SFTP - Letzter Zyklus not used

### ISSUE THREAD

**Issue by EnvidatecFS** [OpenJEVis/JEVis#1893]
The "Letzter Zyklus" is not in use.

**Comment by EnvidatecFS** [comment]
The will most likely also effect which file will be read each readout.

**Comment by gschutz84** [comment]
the datacollector is using the last cycle attribute as intended for all data sources.
last read attribute from channel ist used correctly with sftp datasource as it was
