### ISSUE TITLE
JECC - Analysis - Ukrainian translation for color dialog is missing

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1908]
![grafik](https://user-images.githubusercontent.com/6728123/95090381-7e5adb00-0725-11eb-9f3b-543edacb3a0a.png)

**Comment by EnvidatecFS** [comment]
Ist der JAVA eigene Dialog da haben wir nichts selber übersetzte bzw können nichts übersetzen. Vieleich haben wir glück und er hat nur wieder probleme das UK locale zu erkennen,

**Comment by EnvidatecNH** [comment]
dann ist es möglicherweise ein Systemdialog, der auf einem ukrainischen Windows auch übersetzt ist. Prio ist niedrig, Farben sind selbsterklärend
