### ISSUE TITLE
JECC - Dashboard - Das Sperren mit dem Schloss-Symbol klappt oft nicht

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1911]
Das Sperren mit dem Schloss-Symbol klappt oft nicht

**Comment by EnvidatecFS** [comment]
Wie provozier ich das? Ich glaube es auch schon gesehen zu haben kann es aber gerade nicht nachstellen.

**Comment by EnvidatecFS** [comment]
Konnte mit Gerrit zusammen nicht reproduziert werden. Aber ihm es der Fehler auch schon aufgefallen.

**Comment by gschutz84** [comment]
duplicate #2163
