### ISSUE TITLE
JECC - Dashboard - wenn man im geschützen Modus ein Plugin-Editor öffnen will kommt nur "Message" als Fehlermeldung

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#1919]
wenn man im geschützen Modus ein Plugin-Editor öffnen will kommt nur "Message" als Fehlermeldung

**Comment by EnvidatecFS** [comment]
Kann ich nicht reproduzieren.

Im geschützten modus kann ich keine Widget Editor mit doppelklick öffnen.
Im geschützten modus kann ich den Widget Editor über die Navigation öffnen ohne Fehler.

**Comment by EnvidatecFS** [comment]
OK es passiert nur bei Value Feldern.
