### ISSUE TITLE
JECC - MxB helper does not work

### ISSUE THREAD

**Issue by EnvidatecFS** [OpenJEVis/JEVis#1928]
The Tree (Strg+Shift +M) helper does not work anymore, throws an error.

**Comment by gschutz84** [comment]
It works the same as always, select diff or not, enter a multiplier and select a date

**Comment by EnvidatecFS** [comment]
No my problem was thet it dod not open but throws an error in the consol.
but if i made a test now the dialo will open so i dont know if fixed or happen oly sometimes.

**Comment by gschutz84** [comment]
you fixed it some weeks ago, there was a missing break in the switch i think

**Comment by EnvidatecFS** [comment]
OK
