### ISSUE TITLE
Unit symbol for liter must be 'l' instead of 'L'

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#193]
Unit symbol for liter must be 'l' instead of 'L'

**Comment by gschutz84** [comment]
thats from the unit library, there its a capital L

**Comment by EnvidatecFS** [comment]
"L" is not wrong and would need a workaround to change because of the library.
WIKI: In 1979, at the 16th CGPM conference, the alternative symbol L (uppercase letter L) was adopted
