### ISSUE TITLE
JECC - Analysen - Cannot load Analysis

### ISSUE THREAD

**Issue by EnvidatecFS** [OpenJEVis/JEVis#1970]
The analysis (FuE ID: 20635) cannot be loaded because of some nullpointer.

**Comment by gschutz84** [comment]
was soll das bedeuten? 20635 ist keine analyse sondern ein clean data objekt

**Comment by EnvidatecFS** [comment]
Zahlendreher 20653

**Comment by gschutz84** [comment]
fixed
