### ISSUE TITLE
JECC - DashboardPlugin - Switching from one dashboard to the other does not considers the right time settings

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#2174]
Switching from one dashboard to the other does not considers the right time settings -> as for analyses, the periode and time range should be kept if one switches from one dashboard to the other. Currently, if dasboard A is set to week (which end on the 28.03.2021) and one switches to dashboard B which is set to day by default, dashboard B is shown as day (28.03.2021), but should be the week accordingly to dashboard A.

**Comment by gschutz84** [comment]
man kann nicht beides haben, entweder gibt es einen standard-zeitbereich der geladen wird wenn man ein dashboard auswählt oder es wird der aktuell aktive zeitbereich genommen. da hab ich mit s auch schon drüber diskutiert

**Comment by gschutz84** [comment]
duplicate
