### ISSUE TITLE
JECC - Diagram editor -> cannot change the name of diagram 2-n HIGH PRIORITY

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#219]
Diagram editor -> cannot change the name of diagram 2-n -> only the 1st diagram can be namend

**Comment by gschutz84** [comment]
There is a safety measure, that you can only edit the name of a diagram with selected rows. Unfortunately it's not working as intended, with a new diagram its working right but if you load an existing one, you have to unselect and reselect a data row to enable the edit function

**Comment by EnvidatecNH** [comment]
What is the safety measure for? Does not sound dangerous to change name of a diagram without content -> not explainable to clients
