### ISSUE TITLE
JECC - ChartPlugin - Displaying of kWh as W does not work

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#2343]
Displaying of kWh as W does not work

**Comment by gschutz84** [comment]
its working, please specify

**Comment by EnvidatecNH** [comment]
Check Envidatec EN4 on FuE server -> Medienlastgang -> change to W

**Comment by gschutz84** [comment]
yes, i found it. just the wrong factor. your wording was strong, it seemed more like everything breaks or something
