### ISSUE TITLE
JECC - Analysis - Load Analysis -> Filter for folders

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#2362]
If a user sees different analysis folders he can filter within the names, but cannot just see the analysis of one folder. Maybe we can add a drop down "Folder Filter" menu to see "All" (default) or just the selected. Very comarable to the class filter in the configuration tree.

-> TBD

**Comment by gschutz84** [comment]
it should filter the folder name, too, if not its a bug

**Comment by EnvidatecNH** [comment]
Did not work for me yesterday - nevertheless this feature is an additional one we should discuss
