### ISSUE TITLE
JECC - Schemes Plugin - hash code of passwords are visible

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#242]
if selecting a password, the hash code is visible -> is this a risk, i.e. can an admin reproduce the individual password of a user (which he might use also for other services) -> I guess not, but please verify

**Comment by EnvidatecFS** [comment]
Schemes plugin does not have an password field. Which password do you mean?

The User passwords are are salted ( https://en.wikipedia.org/wiki/Salt_(cryptography) ) so there should be save from any user even an admin.
