### ISSUE TITLE
JECC - ChartPlugin - Limit check does counts the time correctly

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#2431]
In one example I have checked a limit of 80 kW, the dialog says that the load was 2 hours above, but only 2 15-minute values are really over that limit.

After that I checked a limit of 0 kW which shows this result:
![grafik](https://user-images.githubusercontent.com/6728123/179718625-cc9f3355-731d-45e4-a29e-b5ce26e97f9e.png)

All values are above 0 kW, thus the Answer should be 8,760h, it seems that everything is counted twice 17,520h (-2) = 17,518

**Comment by EnvidatecNH** [comment]
My fault, data series was 2 years long.. but it seems that in one year always 1 hour (or sometimes more) is missing:

![grafik](https://user-images.githubusercontent.com/6728123/179720842-cd5a8f45-7c4b-4f22-9ad0-f01914958b7f.png)

![grafik](https://user-images.githubusercontent.com/6728123/179720753-ae22c7af-a18e-4594-ade3-46dacd28e810.png)

Both series are without gaps (from energy utilization company) and manually cross-checked

**Comment by EnvidatecNH** [comment]
see also on the left side, the value is more hours below the limit as possible (year = 8760h):

![grafik](https://user-images.githubusercontent.com/6728123/179721498-2b0d641a-12b5-4e7e-a958-4261c60345c1.png)

**Comment by gschutz84** [comment]
If its a leap year it should be 8784 hours (feb 29th). And its always 1 year minus 15 minutes because our time presets are from 00:00 XXXX-01-01 to 23:59 XXXX-12-31

**Comment by EnvidatecNH** [comment]
If the zero is counted it is the same as 01.01.xxxx 00:15 to 00:00 01.01.xxxx+1. Evem if that year was a leap year more than 15 Minutes are missing. We can have a look on the exact data together, but I am quite sure that sth is wrong.

**Comment by gschutz84** [comment]
yes, two hours are missing. probably because they get lost in the utc->europe/berlin conversion

**Comment by EnvidatecNH** [comment]
Possible, but normally the hours should be displayed twintimes (from 3 to 2). The original series has all data.

**Comment by gschutz84** [comment]
no it doesnt, loading the data with the sample editor and exporting gives the same number. this is a problem in the webservice-mysql connection. i told this to fs multiple times but he didnt believe me

**Comment by EnvidatecNH** [comment]
Make a separate ticket and set it to a high priority. I can show the use case / data series where it happened, so no space for discussion if it happens.
