### ISSUE TITLE
JECC - ChartPlugin - Heatmap shows daily values, even if the aggregation is set to NONE in the sample editor

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#2433]
![grafik](https://user-images.githubusercontent.com/6728123/179723244-9df13d5b-2699-42a9-982a-a437e4662c17.png)

![grafik](https://user-images.githubusercontent.com/6728123/179723191-e8b6bb5c-a9f1-4959-a5c2-2861cbc4faaf.png)

Addition: I like (if selected) how daily aggregation is shown (1 line = 1 month), but in this case the right axis should not show weekday names

**Comment by gschutz84** [comment]
The heatmap automatically adjusts the aggregation depending on the selected timeframe

**Comment by EnvidatecNH** [comment]
Thats new? I have analyzed long periods as 15 minutes in the past. This is one of the main advantages of this diagramm - being able to understand long periods easily. If one wants to see a year on 15 minutes, we should display ut as wanted. It's completly not-understandable for the user. Nonother diagramm in Analysis overrules the choosen set of the user.

**Comment by EnvidatecNH** [comment]
Was never a problem to load half a year via "this year" before. Anyhow, let's change it. The user shall select how to see.

**Comment by gschutz84** [comment]
the canvas size is limited by java. so it was limited by the aggregation to avoid this issue

**Comment by EnvidatecNH** [comment]
If it is technically limited (which is really a pitty), I sugwstbsome user feedback, such as a dialog "Diagramm type is limitted to ..." instead of just making something else as selected. Whatvis the maximum size / duration possible?
