### ISSUE TITLE
JECC - Analysis - Saving of new analyses does not work

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#2486]
Saving of new analyses does not work -> dialog does not close

**Comment by EnvidatecNH** [comment]
It seems that the analysis is saved, but dialog does not close, also the path to the analysis directory is not shown correctly in all cases

**Comment by gschutz84** [comment]
Could be a user rights problem?

**Comment by EnvidatecNH** [comment]
No, I used the JSC user. The analysis was saved, just the dialog does not close, thus it seems that it was not stored

**Comment by gschutz84** [comment]
Okay, as this is the first, probably some other circumstances occured together to cause this, because we are saving a lot, regularly. Need to take a look but as the whole thing is on overhaul, don't know if we should put work into this

**Comment by EnvidatecNH** [comment]
yes, no urgent priority
