### ISSUE TITLE
JECC - Analysis - Calculation of data incl./excl. a time should show the sum as kWh if kW is analyzed

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#2487]
![grafik](https://user-images.githubusercontent.com/6728123/192480432-3bef9ea0-4f3b-4fe1-8670-2a6a517ef583.png)

**Comment by EnvidatecNH** [comment]
Number of values also has an error in 2 cases, s. above

**Comment by gschutz84** [comment]
Without looking at the data, the values look fine? Please specify the errors (assuming the kW->kWh conversion is not one of the errors)

**Comment by EnvidatecNH** [comment]
The sum cannot be kW, must be in kWh. 

"Number of values" shows 0.

**Comment by gschutz84** [comment]
yes, this doesnt convert to the sum unit (if it exists) as of yet. "Amount of values 0" = 0 is possible
