### ISSUE TITLE
JECC - Analysis - If kW is choosen, but the period is >1h the diagram should show kWh

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#2512]
otherwise it makes no sense / nobody understands intuitively the sense of what he sees, such as:

![grafik](https://user-images.githubusercontent.com/6728123/197076872-18d3d644-ab60-4a11-a9a6-f48dafb2d97a.png)

**Comment by EnvidatecNH** [comment]
it seems that the kW shows the average value of the day/week/whatever but that is not intuitive / not needed in most use cases

**Comment by gschutz84** [comment]
This seems to be a reoccurring topic. For other units which are not quantities like temperature, pressure, etc. it is only logical to get the average values if you aggregate the time. So it makes no sense to treat Watts differently? If you want the average kWh you select kWh as a unit
