### ISSUE TITLE
JECC - Configuration - Strg + S to save does not work

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#2513]
Strg + S to save does not work -> afterwards JECC still says that changes are not stored and asks to save

**Comment by EnvidatecFS** [comment]
Its working for me. Must be a bug taht happens only in certain situations. 
We will need information to reproduce this bug.

**Comment by EnvidatecNH** [comment]
If I change the "Time Alginment" button for a clean data this always appears

**Comment by EnvidatecFS** [comment]
Do you mean die "Period Alignment" from the Clean Object? This one ON/OFF Button is working for me with strg+s with Version 3.0.95.
