### ISSUE TITLE
Pool report link object for creating reports  

### ISSUE THREAD

**Issue by Nuttaworn** [OpenJEVis/JEVis#263]
[20180925152800431.pdf](https://github.com/OpenJEVis/JEVis/files/2415400/20180925152800431.pdf)

For configuration report , user have to create report link object individually for each report template, even those report link objects are sometime totally the same.

The idea is the system should has pool report link object which each report can pull the data for creating the report.

![image](https://user-images.githubusercontent.com/41597157/46018137-777e4400-c0d9-11e8-9bb5-1e9aa27f6f7e.png)

![image](https://user-images.githubusercontent.com/41597157/46018171-8b29aa80-c0d9-11e8-9b9f-81b3829e327b.png)

**Benefit** 
1. save the configuration time and decrease human error for bad configuration due to duplicate work for creating a lot report link object.
2. save system resources (cpu + memory) for avoiding duplicated process.

**Comment by gschutz84** [comment]
Normally you create one report link and use copy and paste. The idea behind the value attribute is you can take other attributes like organisation names, address etc. That's not important for an one organisation server but for the big server. The rest of the settings you usually have to configure in any case. If you have a link in one report and need in another again copy and paste with substructure and values. But that's only relevant in one organisation
