### ISSUE TITLE
JECC - Graphs , load analyses custom time interval is not working

### ISSUE THREAD

**Issue by Nuttaworn** [OpenJEVis/JEVis#283]
Custom time intervel for load analyses windows is not working.

![screenshot from 2018-10-10 14-35-48](https://user-images.githubusercontent.com/41597157/46736799-3cb00a80-cc9a-11e8-9477-9b0357c036f0.png)

**Comment by gschutz84** [comment]
If there are no custom time intervals created (configuration), the box is disabled. See other customer for example

**Comment by Nuttaworn** [comment]
ok thx
