### ISSUE TITLE
JEDC - where can i define the interval of the service

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#289]
JEDC - where can i define the interval of the service, means how often the JEDC asks for new jobs/readouts the devices

**Comment by gschutz84** [comment]
The bash in bin/jedataprocessor or the other ones. Change parameter -ct XXX or --cycle-time XXX 
XXX in milliseconds

The process runs, then it waits for this time and starts again

After changing the bash restart service with sudo systemctl

**Comment by EnvidatecNH** [comment]
where is this bin directory?

**Comment by EnvidatecNH** [comment]
answer: ~/jevis/bin
