### ISSUE TITLE
JECC - Analysen sollten sich immer auf die maximale Fensterhöhe vergrößern bzw. verkleinern [Prio Hoch]

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#298]
Beim Vergrößern muss sich an die Fensterhöhe orientiert werden, beim verkleinern darf die minimalgröße nicht unterschritten werden -> d.h. maximal auf die minimalgröße verkleinern

**Comment by EnvidatecFS** [comment]
Implemented.
