### ISSUE TITLE
JECC - Diagramm - Minimale Größe muss etwas größer [Hohe Prio]

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#305]
Minimale Größe muss etwas größer -> zu disktuieren

-> super wäre es wenn man eine Minimalgröße (für 1 Datenreihe) hat und dann für jede zusätzliche Datenreihe die Minimalgröße um x-Pixel (=Höhe für eine Datenreihe in der Header-Tabelle) erhöht

**Comment by EnvidatecFS** [comment]
fixed, also added an auto size function.
