### ISSUE TITLE
JECC - Diagramme - JSON von Analyse wird beim speichern abgeschnitten wenn zu groß

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#309]
JSON von Analyse wird beim speichern abgeschnitten wenn zu groß

=> hier wäre ein Check und Rückmeldung gut, wenn die Analyse nicht gespeichert werden kann

=> die Anzahl von maximalen Diagrammen  und Datenreihen pro Diagramm solllte definiert werden, z.B. erstmal maximal 4 Diagramme und max 8 Datenreihen pro Diagramm

**Comment by gschutz84** [comment]
Check und Rückmeldung ist eingebaut
Anzahl Diagramme auf 4 begrenzt
Datenreihen lassen sich technisch nicht ohne weiteres begrenzen.
