### ISSUE TITLE
JECC - Saving Analyses / multiple directories [LOW Priority]

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#323]
Might be a bug or just a question:

what happens if a user has access to 2 analysis directories? for loading it should be no problem, but where will the save dialog put the saved analysis? 

Use case: a user has an analysis directory shared with a group of users and  a personal analysis directory - some of the analyses he wants to share with the group

=> LOW PRIORITY until we have a real need for this

**Comment by gschutz84** [comment]
will be saved to the first analyses directory id-wise atm
