### ISSUE TITLE
JECC - Diagramme - Tageswerte berücksichtigen den individuellen Tagesanfang/-ende nicht

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#386]
Tageswerte berücksichtigen den individuellen Tagesanfang/-ende nicht, d.h. wenn man im Datenauswahl-Dialog "Täglich" auswählt gehen die Tage immer von 0 bis 24h

=> müsste man eigentlich für Wochenstart usw auch durchziehen -> vorher mal diskutieren

**Comment by gschutz84** [comment]
bei der aggregation werden die summen immer auf den zeitstempel des ersten intervalls der periode geschrieben z.b. bei monatswerten der 01.10.2018 00:00:00
