### ISSUE TITLE
JECC - Die URL auf die der Begrüßungs-Pop-Up-Dialog zugreift sollte im JECC konfigurierbar sein

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#397]
Die URL auf die der Begrüßungs-Pop-Up-Dialog zugreift sollte im JECC konfigurierbar sein, vielleicht bei den Services oder was ähnliches?!

**Comment by EnvidatecFS** [comment]
Läst sich bereits mit dem Startparameter "--welcomeurl=https://meinetolleurl.de" setzen. Setzen im Service wäre möglich , müsste dann aber ein Öffentliches Object sein und wäre für alle gleich.  Bei der Benutzergruppe wäre es variabler.

**Comment by EnvidatecNH** [comment]
Als Startparameter reicht
