### ISSUE TITLE
JECC - Diagramme - Darstellung der Daten mit Glättung/gleitender Mittelwert [

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#421]

**Comment by EnvidatecNH** [comment]
Als "live" Funktion im Graph? Als zusätzliche Aggregation? Als weitere Einstellung am Clean Data Object?

Aktuell nicht wichtig => später diskutieren

**Comment by gschutz84** [comment]
das gibts schon halb in der aggregationsfunktion, muss quasi nur freigeschaltet werden.
ursprünglich war das für das chart settings tab pane gedacht
