### ISSUE TITLE
JECC - Diagramme - die "Optik" der Manipulations-Logos optimieren

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#460]
die "Optik" der Manipulations-Logos optimieren
Ideen sammeln:
* andere Logos?
* nur "Farbcode" mit weißem Rand?

**Comment by gschutz84** [comment]
man kann die buchstaben auch aus den lokalisierungsdateien holen, wären dann keine bilder, könnte auch die performance verbessern
