### ISSUE TITLE
JECC - Keine Rechte auf eigenen Ordner nach dem Anlagen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#463]
Wenn man ein Ordner anlegt (Beispiel: Berechnungsordner) hat man danach keine Rechte auf diesen, kann hier z.B. nichts anlegen oder den Ordner umbenennen, nach Logout+Login geht es

**Comment by EnvidatecFS** [comment]
Wurde gefixed.
