### ISSUE TITLE
JECC - Diagramme - Analysen werden gecached / Datenmodell-Attribut muss vor dem Laden aktualisiert werden

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#465]
Analysen werden gecached / Datenmodell-Attribut muss vor dem Laden aktualisiert werden, falls in der Zwischenzeit etwas (Diagrammtitel, Datenreihen, o.ä.) geändert wurde

**Comment by gschutz84** [comment]
müsste seit 3.5.7 raus sein? bitte nochmal testen, ließ sich leider nicht reproduzieren
