### ISSUE TITLE
JECC - Clean Object - Umwandlung zu Differenziell muss manuell über den Sample Editor gesetzt werden, wenn der Wert deaktiviert sein soll

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#467]
Umwandlung zu Differenziell muss manuell über den Sample Editor gesetzt werden, wenn der Wert deaktiviert sein soll -> evtl. beim anlegen per Default eine 0 auf 2001-01-01 00:00:00 setzen?

**Comment by EnvidatecFS** [comment]
Richtige Lösung würde in Richtung Template System gehen, war wieder recht aufwändig wäre. ein "if case" workaround wäre möglich.

**Comment by EnvidatecNH** [comment]
Ich denke wir sprechen nicht vom selben: wenn man ein Clean Object anlegt hat das "Umwandlung zu Differenz" Attribut kein Wert, d.h. weder "0" noch "1", angezeigt wird aber "Aus" (=0).

Ich nehme an der DataProcessor arbeitet mit "0" wenn nichts gesetzt wird? Aber warum setzen wir die "Defaults" die wir im DataProcessor definiert haben "wenn nichts da ist" nicht gleich beim anlegen eines Objects (GUI Seitig: wenn angelegtes Object = Clean Object, dann mach zusätzlich Attribut x = 0, y=1.0, usw)?

**Comment by EnvidatecNH** [comment]
ich nehme an letzteres meinst du mit "if case" workaround -> wäre für mich ok

**Comment by gschutz84** [comment]
da haben wir letzten mittwoch drüber gesprochen. dadurch dass du die ganzen try {} catch {} entfernt hattest, throwed er da immer eine exception statt disabled anzunehmen...

**Comment by gschutz84** [comment]
Gilt auch für das Mengeneinheit Attribut
