### ISSUE TITLE
JECC - immer wenn man die Konfiguration öffnet ist der Analysen-Ordner schon aufgeklappt

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#472]
immer wenn man die Konfiguration öffnet ist der Analysen-Ordner schon aufgeklappt - muss das so sein?

**Comment by EnvidatecNH** [comment]
Ist immer noch so

**Comment by EnvidatecFS** [comment]
Ich kann den Fehler nicht nachvollziehen. Ist der Fehler noch vorhanden, wenn ja brauchte ich eine bessere Fehlerbeschreibung.

**Comment by EnvidatecNH** [comment]
Ja, ist bei mir mit einem normalen User immer reproduzierbar

1. als JSC anmelden
2. Konfiguration öffnen
3. Analyse ist aufgeklappt
