### ISSUE TITLE
JECalc - DIV/0 Verhalten am Kalkulations Objekt parametrierbar machen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#502]
Es wäre cool, wenn man jeweils am Kalkulationsobjekt parametrieren könnte, wie mit dem DIV/0 Fall umgegangen werden soll (Stopp, Lücke, Ersatzwert). 

Egal welches Verhalten gewählt wurde wird DIV/0 im Graph durch ein Icon angezeigt.

**Comment by gschutz84** [comment]
doppelt
