### ISSUE TITLE
JECC - Diagramme - der Info-String im Header sollte zentriert sein

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#503]
der Info-String im Header sollte zentriert sein

**Comment by gschutz84** [comment]
elaborate please

**Comment by EnvidatecNH** [comment]
Es bezieht sich nur auf die Spalte mit der Überschrift "Info", wenn hier z.B. "0" steht ist diese an den linken Rand gequetscht, zentriert sähe sauberer aus, wenn mehr auftaucht, z.B. "L2 G N" könnte dieser genauso zentriert dargestellt werden -> evtl. reden wir aneinander vorbei?
