### ISSUE TITLE
JECC - Diagramme - Vielen Daten werden erst nach speichern der Analyse angezeigt

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#504]
Vielen Daten werden erst nach speichern der Analyse angezeigt:

1. bestehende Analyse laden
2. bestehende Analyse umkonfigurieren und laden
-> nicht alle Datenreihen zeigen Daten obwohl Daten da sind
3. Analyse speichern
-> danach werden überall Daten angezeigt

Ist der Bug evtl. nur einmalig auf Grund alter/neuer Datenmodelle?

**Comment by gschutz84** [comment]
das wäre möglich, kann aber auch an der dynamischen diagramm befüllung liegen
