### ISSUE TITLE
User Class - sind die Attribute "Sprache" und "Zeitzone" überflüssig?

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#670]
sind die Attribute "Sprache" und "Zeitzone" überflüssig?

Sprache -> wird beim Login geregelt
Zeitzone -> bezieht sich auf den analysierten Standort

**Comment by EnvidatecFS** [comment]
Ich könnte mir schon Funktionen vorstellen wo die Attribute sinn machen aber zur Zeit haben wir keine. Wurde damals aus Look&Feel gründen eingebaut.
