### ISSUE TITLE
JECC - CSV-Import importiert nicht in der Vergangenheit sondern überschreibt aktuelle Werte [Kritisch]

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#675]
-> konkretes Beispiel muss besprochen werden

**Comment by gschutz84** [comment]
Daran erinnere ich mich. Als ich da dran war, habe ich gefragt ob es beim Überschreiben bleiben soll oder nicht.

**Comment by gschutz84** [comment]
sollte nicht passieren, test nötig
