### ISSUE TITLE
JEDataProcessor - Cleandaten von Berechnungen, z.B. EnPIs hängen den Messwerten 1 Periode nach?

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#680]
Cleandaten von Berechnungen, z.B. EnPIs hängen den Messwerten 1 Periode nach? Der Messwert wird bis 11:30 angezeigt um 11:40 aber die EnPI steht noch auf 11:15 -> evtl schon gelöst?

**Comment by gschutz84** [comment]
also da sollte es keinen unterschied zu ausgelesen roh daten objekten geben? ist das da auch so?

**Comment by gschutz84** [comment]
und config oder graph?

**Comment by EnvidatecNH** [comment]
charts

**Comment by EnvidatecNH** [comment]
Evtl hängt es am JECalc? Also vielleicht fängt der erst an zu rechnen, wenn 2 neue Samples da sind o.ä. -> können wir mal versuchen nachzustellen

**Comment by EnvidatecNH** [comment]
Sorry, war charts und config, also keine Daten angezeigt und auch keine im Sample Editor zu sehen
