### ISSUE TITLE
JEWebService/JEAPI-WS - Es sind besondere Rechte-Regeln für Raw/Clean Data und Notizen notwendig

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#711]
-> Diskussion

**Comment by EnvidatecFS** [comment]
Webserver seitig gibt es leider keine unterschied zwischen Raw/Clean oder jedem anderem Daten. Es wäre möglich ein weiteres Attribut bei user einzubauen ähnlich wie das "Sys Admin" attribute. Dies wäre das wie eine rolle.

Alternativ wäre es möglich in den JEVisControlCenter Optionen eine option "Experten Modus" einzubauen so das der User bewusst die Option aktivieren muss und nicht aus versehen roh Daten löscht, böte in der form auch selbst bei JSC Mitarbeitern den forteil der sicherheit.
