### ISSUE TITLE
JECC - Diagramme - wenn man im 2. Diagramm reinzoomt und per Schnellauswahl in eine andere Analyse springt, bleibt der zoom im 2. Diagramm bestehen, d.h. man muss rauszoomen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#720]
wenn man im 2. Diagramm reinzoomt und per Schnellauswahl in eine andere Analyse springt, bleibt der zoom im 2. Diagramm bestehen, d.h. man muss rauszoomen

**Comment by gschutz84** [comment]
doppelt
