### ISSUE TITLE
JECC - Lückenbefüllung schreibt die Standard-Konfiguration erst wenn man die Konfiguration dazu öffnen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#739]
Lückenbefüllung schreibt die Standard-Konfiguration erst wenn man die Konfiguration dazu öffnen -> wäre gut wenn er den Standard reinschreibt, wenn man nur einfach "An" klickt.

**Comment by gschutz84** [comment]
gleiches für die grenzwert konfiguration
