### ISSUE TITLE
JEVis Control Center - CSV import does not remember the date settings

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#77]
der CSV Import sollte die Einstellungen "date time" etc. merken wenn man
nur ein nächstes File aussucht, da es sehr wahrscheinlich ist, dass das
nächste File die gleiche Struktur hat

**Comment by EnvidatecFS** [comment]
Problem is that Windows 10 does not support the good old way to store settings anymore in JNLPs
