### ISSUE TITLE
JEAPI-WS - wenn man eine Analyse löscht ist sie in der aktuellen Sitzung weiter vorhanden und funktioniert auch

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#794]
wenn man eine Analyse löscht ist sie in der aktuellen Sitzung weiter vorhanden und funktioniert auch -> erst nach logout/login ist sie für den Benutzer wirklich weg.

**Comment by gschutz84** [comment]
ds.deleteObject(id) doesn't seem to work properly without starting .preload() or reloading program

**Comment by gschutz84** [comment]
Es verursacht auch andersrum Probleme. Wenn man eine Analyse erstellt und die dann direkt verlinkt und drauf zugreifen möchte ohne das Programm neu zu starten, funktioniert es nicht, weil er sie zwar findet aber die Attribute sind null, obwohl da ja angeblich etwas drin ist

**Comment by EnvidatecFS** [comment]
fixed in Analysis but will not update other plugins for now.
