### ISSUE TITLE
JECC - Diagramme - Darstellungsfehler nachdem ein Screenshot von aggregierten Daten gemacht wird

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#831]
Darstellungsfehler nachdem ein Screenshot von aggregierten Daten gemacht wird -> wenn man z.B. Daten als Stunden- oder Tagesaggregation lädt und dann ein Screenshot speichert, ist das Screenshot richtig, aber danach gibt es willkürlich eins der folgenden Probleme, welche nur mit Neustart des Programms zu behebend:

Fehlerfall 1: Es wird riesig in das oberste Diagramm gezoomt
Fehlerfall 2: Am rechten Bildschirmrand entsteht ein weißer Bereich der nicht mehr genutzt wird

**Comment by gschutz84** [comment]
Sollte zumindest nur Fehlerfall 1 auftreten, genaues Problem ist nocht unbekannt. Workaround ist aber nicht Programm neustarten, sondern einfach Programmfenstergröße ändern. Z.B. 2x Doppelklick auf Programmtitelleiste.

**Comment by gschutz84** [comment]
es tritt auch nur das erst mal wenn man die screenshot funktion nutzt auf.
