### ISSUE TITLE
JECC - Diagramme - nach dem Programmstart, wenn man eine Analyse lädt steht die Einstellung auf "Heute", im Hintergrund werden aber von der aktuellen Zeit die letzten 24 Std. geladen, was dazu führt das "Heute" nochmal geladen werden muss wenn man bestätigt 

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#835]
nach dem Programmstart, wenn man eine Analyse lädt steht die Einstellung auf "Heute", im Hintergrund werden aber von der aktuellen Zeit die letzten 24 Std. geladen, was dazu führt das "Heute" nochmal geladen werden muss wenn man bestätigt -> kann man evtl. gleich "Heute" anzeigen und wenn man dann einfach weiter durchklickt ist kein erneutes laden notwendig? 

-> Prio: Niedrig

**Comment by gschutz84** [comment]
die preview funktion zeit fest die letzten 24h an Daten in der Datenreihe an, wenn "Heute" geladen werden soll, ist das bei fehlenden Daten komplizierter
