### ISSUE TITLE
JECC - Ist es gewollt, dass man automatisch auch die Clean Daten löscht wenn man die Werte des Raw Data löscht?

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#845]
Ist es gewollt, dass man automatisch auch die Clean Daten löscht wenn man die Werte des Raw Data löscht?

-> ist oft praktisch, aber evtl, in manchen Anwendungsfällen gefährlich? -> TBD

**Comment by EnvidatecFS** [comment]
Ich brauche mehr Infos zum Usecase und das verhalten zu reproduzieren.
Meines Wissens gibt es keine Funktion die so etwas macht bzw machen kann.
