### ISSUE TITLE
JECC - Dashboard - Torten fehlen teilweise die Beschriftungen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#850]
Torten fehlen teilweise die Beschriftungen -> z.B. hat eine Torte 5 Tortenstücke, aber bei 2 von 5 fehlt der Marker mit % und kWh Angabe

**Comment by EnvidatecFS** [comment]
sollte gefixed sein durch den erhöhten Abstand in gug #856

**Comment by EnvidatecFS** [comment]
Kann leider immer noch passieren.

**Comment by EnvidatecFS** [comment]
Es gibt keinen zufriedenstellende Lösung für das Problem zur Zeit. Java update bzw wechsel zu einer andere lib könnte helfen.
