### ISSUE TITLE
JECC - JEConfig.getLastPath() und JEConfig.setLastPath() are deprecated. Needs to be reworked with functionality for different os

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#855]
Diagramme - es wäre schön wenn sich der Screenshot Dialog den letzten Ordner merkt, z.B wenn man viele Screenshots macht

**Comment by gschutz84** [comment]
JEConfig.getLastPath() und JEConfig.setLastPath() are deprecated...
