### ISSUE TITLE
JECC - Diagramme - Analyse-Link” Knopf im Dashboard reagiert nach Neustart erst nach dem 2. Klick

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#857]
Analyse-Link” Knopf im Dashboard reagiert nach Neustart erst nach dem 2. Klick -> beim ersten mal klicken öffnet zwar der Analysen-Reiter, es passiert aber nichts (danach ist die Analye meist auch in der Darstellungsart oder Überschriften fehlerhaft)

**Comment by EnvidatecNH** [comment]
Die falsche Darstellungsweise korrigiert sich meist mit dem Reload-Button (allerdings nicht die Überschriften)

**Comment by EnvidatecFS** [comment]
Bug ist im Diagramme
