### ISSUE TITLE
JECC - Diagramme - Der “Analyse-Link” Knopf verursacht generell Probleme in den Analysen

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#860]
Der “Analyse-Link” Knopf verursacht generell Probleme in den Analysen -> es scheint als wenn der ganze Analysen Reiter viel mehr Bugs hat nachdem man einmal den "Analysen Link" Knopf benutzt hat

**Comment by EnvidatecFS** [comment]
Problem ist in den Diagrammen nicht im linker
