### ISSUE TITLE
JECC - Analysen - "Play"-Knopf stellt auf dem selben System (bei 2 unterschiedlichen Benutzern) einmal 900s und einmal 3600s ein

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#939]
"Play"-Knopf stellt auf dem selben System (bei 2 unterschiedlichen Benutzern) einmal 900s und einmal 3600s ein -> woran er das fest macht ist unklar

**Comment by gschutz84** [comment]
auf dem einen system stand die aggregation auf stunde, bei dem anderen auf none.
3600s = 1h
900s = 15min
