### ISSUE TITLE
Compiling Error Installation

### ISSUE THREAD

**Issue by MuschelInBlau** [OpenJEVis/JEVis#986]
Hello everyone,

i have an error with the installation of jevis... Current Java is v11

`[INFO] 100 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JEVis Core 3.4 ..................................... SUCCESS [  0.003 s]
[INFO] JEAPI 3.1.4 ........................................ SUCCESS [  3.050 s]
[INFO] JECommons 3.28 ..................................... FAILURE [  4.963 s]
[INFO] JEAPI-WS 1.24 ...................................... SKIPPED
[INFO] JEWebservice 1.8 ................................... SKIPPED
[INFO] JEVisControlCenter 3.8.4 ........................... SKIPPED
[INFO] DataCollector 3.0.0 ................................ SKIPPED
[INFO] JEDataCollector 3.0.8 .............................. SKIPPED
[INFO] CSVParser 1.2.3 .................................... SKIPPED
[INFO] FTPDataSource 1.0-SNAPSHOT ......................... SKIPPED
[INFO] HTTPDataSource 1.1-SNAPSHOT ........................ SKIPPED
[INFO] sFTPDataSource 1.0-SNAPSHOT ........................ SKIPPED
[INFO] SOAPDataSource 1.0-SNAPSHOT ........................ SKIPPED
[INFO] XMLParser 1.0.1 .................................... SKIPPED
[INFO] JECalc 1.0.1 ....................................... SKIPPED
[INFO] Notifier 3.0.0 ..................................... SKIPPED
[INFO] Notifier 1.0 ....................................... SKIPPED
[INFO] Notifier-EP 1.0 .................................... SKIPPED
[INFO] JENotifier 1.0 ..................................... SKIPPED
[INFO] JEReport 1.1.2 ..................................... SKIPPED
[INFO] JEDataProcessor 1.5 ................................ SKIPPED
[INFO] JEStatus 1.0 ....................................... SKIPPED
[INFO] JEAlarm 1.0 ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.755 s
[INFO] Finished at: 2019-06-21T07:09:55Z
[INFO] ------------------------------------------------------------------------
`

**Comment by gschutz84** [comment]
Hi,
try using Java 8 SDK for compiling.

**Comment by MuschelInBlau** [comment]
Can't install java 8 because it isn't in repository.... i tried the install manual in the wiki...

**Comment by gschutz84** [comment]
oracle changed their license this year, which had a lot of repercussions. like this ppa distro getting discontinued.
you can try to get the installation package from oracle, but you need an account.

**Comment by MuschelInBlau** [comment]
Ok i installed it succesfully now i have the problem with the database install:
Install the Database

mvn compile flyway:migrate

[ERROR] No plugin found for prefix 'flyway' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/jevis/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]

**Comment by EnvidatecFS** [comment]
You have to be in the "mysqldb" sub folder for this command. 

The project structure changed a bit and we have yet to update the installation manual. I will install an new system next week, so i could take the chance to update the manual then.

**Comment by MuschelInBlau** [comment]
in the folder i get this error.....

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mysqldb: Compilation failure
[ERROR] /home/jevis/jevis/mysqldb/src/main/java/org/jevis/App.java:[11,9] cannot find symbol
[ERROR]   symbol:   variable logger
[ERROR]   location: class org.jevis.App
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by EnvidatecFS** [comment]
The was an missing symbol which was left from an code cleanup. Pull again to get the fix or remove the `logger.info("Hello World!"); line in the mysqldb/src/main/java/org/jevis/App.java file.

**Comment by MuschelInBlau** [comment]
Next....
[ERROR] Migration of schema `jevis` to version 7 failed! Please restore backups and roll back database and code!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.105 s
[INFO] Finished at: 2019-06-27T10:43:02Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:migrate (default-cli) on project mysqldb: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException:
[ERROR] Migration V7__Alter_Sample_Value_Size.sql failed
[ERROR] ------------------------------------------------
[ERROR] SQL State  : 42000
[ERROR] Error Code : 1074
[ERROR] Message    : Column length too big for column 'value' (max = 21845); use BLOB or TEXT instead
[ERROR] Location   : db/migration/V7__Alter_Sample_Value_Size.sql (/home/jevis/jevis/mysqldb/target/classes/db/migration/V7__Alter_Sample_Value_Size.sql)
[ERROR] Line       : 3
[ERROR] Statement  : alter table sample modify value varchar(40000)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by gschutz84** [comment]
fixed, please pull again

**Comment by MuschelInBlau** [comment]
[INFO] Validated 7 migrations (execution time 00:00.088s)
[INFO] Current version of schema `jevis`: 7
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.403 s
[INFO] Finished at: 2019-06-28T11:26:40Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:migrate (default-cli) on project mysqldb: org.flywaydb.core.api.FlywayException: Schema `jevis` contains a failed migration to version 7 ! -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by EnvidatecFS** [comment]
The was an missing symbol which was left from an code cleanup. Pull again to get the fix or remove the `logger.info("Hello World!"); line in the mysqldb/src/main/java/org/jevis/App.java file.

**Comment by EnvidatecFS** [comment]
My guess is that fix for the "V7__Alter_Sample_Value_Size.sql"  has now an different hash than before. To fix this drop the database and re run the script: 
`
mysql> drop database jevis;

mysql> create database jevis;
`

**Comment by MuschelInBlau** [comment]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:migrate (default-cli) on project mysqldb: org.flywaydb.core.api.FlywayException: Schema `jevis` contains a failed migration to version 7 ! -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
...

**Comment by EnvidatecFS** [comment]
I'm just waiting for the new hardware to update the manual.
You can try to use the debug option "mvn -X compile flyway:migrate".

**Comment by MuschelInBlau** [comment]
I wait for the next install manual... there are so much errors.... :(

**Comment by EnvidatecFS** [comment]
I do not get this error with an fresh Ubuntu Server 18.04.2 LTS installation. I guess its because of the fix to the SQL file and the failed try's before. Try to reset the Flyway db tool use by using _"mvn flyway:clean"_ in the mysqldb directory and then rerun _"mvn compile flyway:migrate"_.

Sorry for the delay but the new machine did not come until yesterday and I'm in pre vacation stress.Its the same reason i cannot finish the installation manual but maybe one of my colleges can.

Maybe its the best we give you an demo account for one of our server if you want to test the software. The whole server side is not end user ready yet and our focus is on the end user side for now. In the current state the JEVis Server side is mostly managed by us and the user using only the front end. 

Can I ask what your background is, do you wanna try the JEVis System out of personal curiosity or do you come from an business or R&D background?

**Comment by EnvidatecNH** [comment]
Wir programmieren Lizenzoffen, aber machen mit den passenden Dienstleistungen unser tägliches Geschäft. In Software ändert sich leider immer schnell das eine oder das andere und die Kollegen die täglich mit den Systemen arbeiten  haben das meiste im Kopf - darunter leidet leider oft die Dokumentation bzw hinkt hinterher.

Wir setzten in einem aktuellen Projekt gerade auch ein komplett frisches System auf und werden in dem Zug auch die Dokumentation hier wieder aktualisieren. Auf Grund von Urlauben bei uns und beim Kunden wird es aber vermutlich vor Anfang August nichts mehr.

**Comment by MuschelInBlau** [comment]
Alles klar :) Dann warte ich erstmal ab
