### ISSUE TITLE
JECC - Diagramme - der Strich auf der x-Achse welcher zu der Zeitangabe gehört sollte deutlicher hervorgehoben werden/fetter sein

### ISSUE THREAD

**Issue by EnvidatecNH** [OpenJEVis/JEVis#993]
der Strich auf der x-Achse welcher zu der Zeitangabe gehört sollte deutlicher hervorgehoben werden/fetter sein

**Comment by gschutz84** [comment]
something is wrong with minor tick marks. not scaling properly. disabled unto further notice.
